# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/aws/amazon-cloudwatch-agent
%global goipath         github.com/aws/amazon-cloudwatch-agent
Version:                1.300028.4

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
CloudWatch Agent enables you to collect and export host-level metrics and logs
on instances running Linux or Windows server.}

%global golicenses      LICENSE NOTICE licensing/LICENSE licensing/NOTICE\\\
                        licensing/THIRD-PARTY-LICENSES\\\
                        plugins/inputs/logfile/tail/LICENSE.txt
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md README.md amazon-\\\
                        cloudwatch-container-insights/cloudwatch-agent-\\\
                        dockerfile/README.md packaging/debian/changelog\\\
                        packaging/debian/changelog.Debian\\\
                        plugins/inputs/logfile/README.md\\\
                        plugins/inputs/logfile/globpath/README.md\\\
                        plugins/inputs/logfile/tail/CHANGES.md\\\
                        plugins/inputs/logfile/tail/README.md\\\
                        plugins/inputs/statsd/README.md\\\
                        plugins/inputs/win_perf_counters/README.md\\\
                        plugins/outputs/cloudwatch/README.md\\\
                        plugins/processors/ec2tagger/README.md\\\
                        receiver/adapter/README.md tool/clean/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        CloudWatch Agent enables you to collect and export host-level metrics and logs on instances running Linux or Windows server

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in tool/clean/clean_dedicated_host tool/clean/clean_ami tool/clean/clean_file_system tool/clean/clean_eks tool/clean/clean_auto_scaling_groups tool/clean/clean_ecs tool/clean/clean_host; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE NOTICE licensing/LICENSE licensing/NOTICE
%license licensing/THIRD-PARTY-LICENSES plugins/inputs/logfile/tail/LICENSE.txt
%doc CODE_OF_CONDUCT.md CONTRIBUTING.md README.md
%doc amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile/README.md
%doc packaging/debian/changelog packaging/debian/changelog.Debian
%doc plugins/inputs/logfile/README.md plugins/inputs/logfile/globpath/README.md
%doc plugins/inputs/logfile/tail/CHANGES.md
%doc plugins/inputs/logfile/tail/README.md plugins/inputs/statsd/README.md
%doc plugins/inputs/win_perf_counters/README.md
%doc plugins/outputs/cloudwatch/README.md plugins/processors/ec2tagger/README.md
%doc receiver/adapter/README.md tool/clean/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
